import '../styles/globals.css'
import Head from 'next/head'
import Footer from './components/footer.js'
import Header from './components/nav.js'
import Box from '@mui/material/Box';
// import styles from '../styles/globals.css'
import styles from '../styles/Home.module.css'
import styles2 from '../styles/Header.module.css'



function MyApp({ Component, pageProps }) {
  return (
    <div>
        <Head>
          <title>Clean & Collect</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          
          {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerPolicy="no-referrer" />
          <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/> */}
        </Head>


        <Box className={styles2.header}></Box>
        <Header />

        <div className={styles.container}>

          <Component {...pageProps} />
        </div>

          
          
        <Footer/>
    </div>
  )
}

export default MyApp